### ISSUE TITLE
Autoplay Classes

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#1704]
https://boldcontentvideo.com/2016/04/29/how-to-set-a-vimeo-video-to-autoplay/

**Comment by diegomaranhao** [comment]
Have you already enabled the autoplay options on each video on Vimeo?
I did some tries here on my dev environment without success and after that, I realized that maybe you need to enable this option.

**Comment by diegomaranhao** [comment]
Hey Renzo, after some research and tests I found some problems and solutions that I will explain here, so you can decide what is better.
First of all, I discovered that all browsers block autoplay by default.
In the face of that, I had visualized some options:
1- You can start the video muted, and if the video starts that way the browser will allow the autoplay
2- You can tell your user to change their web browser configurations to allow autoplay
3- You can just let it as it is right now
