### ISSUE TITLE
Allow users edit their accounts

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#249]

**Comment by Riverfount** [comment]
Here we need a form and view that allows users to do changes in their profiles. Is that?

**Comment by renzon** [comment]
In fact we only need to provide a customisation for the template. Django already has the forms, check framework's docs. Check that for authentication and login I have only used some builtin Class Based Views: https://github.com/pythonprobr/pythonpro-website/blob/master/pythonpro/urls.py#L23 and used the default names for customizazion: https://github.com/pythonprobr/pythonpro-website/tree/master/pythonpro/core/templates/registration

**Comment by Riverfount** [comment]
Ok, I'm studying Class-Based Views and, yes I understand that is so simple to implement. If you need help to implement this features call me, ok!?

**Comment by renzon** [comment]
Go ahead ;)
