### ISSUE TITLE
fix link on-page 'objetos pythônicos - motivação'

### ISSUE THREAD

**Issue by serlus** [pythonprobr/pythonpro-website#2651]
[page link](https://www.python.pro.br/modulos/objetos-pythonicos/topicos/objetos-pythonicos-motivacao)
link on-page is don't available.

**Comment by renzon** [comment]
Será que vc quis dizer o link do post do fórum que fica embaixo da página?

**Comment by serlus** [comment]
Isso, mas na página q te a aula. Pois no fórum o link está ativo. Olhei de relance no Fork q fiz mas a principio não identifiquei. Parece q foi apenas um <p> a mais pelo q vi via Firefox.
