### ISSUE TITLE
Change Python Pro Address

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#2913]
Change from Rua Curação to 👍 
![image](https://user-images.githubusercontent.com/3457115/92014486-b08fac00-ed25-11ea-9a7b-7a1f6b804990.png)

**Comment by Val2021** [comment]
I have tried to find this information at the code, but i didn't find it. Could you tell me where it is?

**Comment by renzon** [comment]
Sorry, this was an issue for the email marketing system, not a code issue. Anyway, thank you for be interested in help.
