### ISSUE TITLE
Fix link to discussion [https://www.python.pro.br/modulos/pytools/topicos/implementacao-conexao-sessao-usuario]

### ISSUE THREAD

**Issue by wfoschiera** [pythonprobr/pythonpro-website#3029]
Continuar Discussão button redirects to: https://forum.python.pro.br/t/pytools-emulando-teste-com-banco-de-dados/305/2.
correct link: https://forum.python.pro.br/t/pytools-implementacao-de-conexao-sessao-e-usuario/306

**Comment by renzon** [comment]
Fixed, thanks for pointing it out
