### ISSUE TITLE
Change on Sendgrid authentication

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#3200]
It seem api key must be used and we need to discover how to configure Django with it. Email received from them:

"

Hello there,

We are emailing to inform you of an upcoming requirement to update your authentication method with Twilio SendGrid to API keys exclusively by December 10th, 2020 in order to ensure uninterrupted service and improve the security of your account. Our records show that one or more users with this email address used basic authentication with username and password for one or more of your SendGrid API requests in the last 30 days. If you do not take action, those API requests will be rejected on December 10th, 2020.

Why API keys?
This is an effort to enhance security for all of our users. Using your account username and password for authentication is less secure than using an API Key. Unlike your username and password, API Keys are uniquely generated and can be set to limit the access and specify permissions for a given request. 

What action is required?
Follow these steps to identify and replace your authentication method to API Keys and then implement Two-Factor Authentication (2FA) for enhanced security.

What happens if no action is taken?
On December 10th, 2020 we will no longer accept basic authentication with username and password, and we will be requiring 2FA to login to your account. If you attempt to authenticate your API requests or SMTP configuration with username and password for any of your users after that date, your requests will be rejected.

We’d like to thank you in advance for your prompt attention to these requirements. If you’d like to learn more about how you can enhance the security of your account, view this post. If you have any questions or need assistance, please visit our documentation or reach out to support.

Thank you,
The Twilio SendGrid Team
"

**Comment by RamiroAlvaro** [comment]
![Captura de Pantalla 2020-11-16 a la(s) 16 15 09](https://user-images.githubusercontent.com/7095750/99299380-ea9f2300-2829-11eb-9b86-5c260858d316.png)
![Captura de Pantalla 2020-11-16 a la(s) 16 17 36](https://user-images.githubusercontent.com/7095750/99299495-0d313c00-282a-11eb-8be6-4e13fe374ee8.png)
![Captura de Pantalla 2020-11-16 a la(s) 16 18 29](https://user-images.githubusercontent.com/7095750/99299535-1ae6c180-282a-11eb-896d-23ed1ba72984.png)

[SendGrid Django Cofig](https://sendgrid.com/docs/for-developers/sending-email/django/)
