### ISSUE TITLE
Bookmark topic feature

### ISSUE THREAD

**Issue by gilsondev** [pythonprobr/pythonpro-website#3249]
When the student wants to return to a previous topic, he does not have an intuitive way to do so. Thus, this issue has the objective of defining this function in which:

Given a logged in student
When to attend a topic class
I want to have a "Mark as favorite" button to access it in the future.

Follow a example:

![image](https://user-images.githubusercontent.com/265653/101079220-f27af900-3585-11eb-9f30-6afd3b7e29b9.png)

In addition to creating a page that will centralize all topics as favorites by the user, for quick access.

**Comment by renzon** [comment]
Very nice feature, thanks for proposing it.
