### ISSUE TITLE
Create an automated certificate page

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#343]
Check how to make them apear on linkedin just like: https://suporte.alura.com.br/article/133-informacoes-do-certificado-nao-aparecem-no-linkedin

**Comment by tiagocordeiro** [comment]
maybe it helps

https://addtoprofile.linkedin.com

LinkedIn API certifications
https://developer.linkedin.com/docs/guide/v2/people/profile-edit-api/certifications
