### ISSUE TITLE
Configure Heroku with Python Pro domain

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#40]
Site will use www.python.pro.br domain. Need to use SSL for user's privacy and also better ranking on Google search

**Comment by Riverfount** [comment]
Well to do this work we need access to Heroku account! Is this possible?

**Comment by renzon** [comment]
We can figure it out latter. To really to that, we need first have a reasonable home page, at least equals of what we have today in www.python.pro.br ;)

**Comment by Riverfount** [comment]
Ok, I'm understanding. You put this issue here for don't forget it!

**Comment by carlos-moreno** [comment]
Regarding the accesses, there is this link https://devcenter.heroku.com/articles/org-users-access that can give some tips on how to do, but I do not know if it will solve the problem completely.

**Comment by renzon** [comment]
already done: www.python.pro.br
