### ISSUE TITLE
Update local docker compose posgtres versions

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#4839]
New django doesn´t work with old postgres:

```
  File "/home/renzo/PycharmProjects/pythonpro-website/.venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 214, in check_database_version_supported
    raise NotSupportedError(
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.5).
```

**Comment by luisgs7** [comment]
Hi Renzo, I can resolve this issue by the end of the week.

**Comment by luisgs7** [comment]
Ok.

Renzo, do you have a video that explains the initial configuration of Python for the website?

I'm having trouble starting the application.

**Comment by renzon** [comment]
I need to acess it on localhost:8000/dashboard. Currently the application is redirecting to pythonpro.com.br on startup. You need also provide a .env with some properties. Use this one as base: https://github.com/pythonprobr/pythonpro-website/blob/master/contrib/env-sample

**Comment by renzon** [comment]
Postgres updated to 15.2
