### ISSUE TITLE
Change config lib from python-decouple to dynaconf

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#5]

**Comment by luzfcb** [comment]
outras opções:

https://github.com/osantana/prettyconf

https://github.com/joke2k/django-environ
do django-environ, eu gostei da api para trabalhar com diretórios, que já está embutida nele

**Comment by renzon** [comment]
Dynaconf was chosen after discussion with the team. I will bring it from dynaconf branch
