### ISSUE TITLE
Subjects to next Tech Talk on Nov 14th

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#50]
@tiagocordeiro @Riverfount I am creating this issue so we can decide what to approach on our next Tech Talk. Just add what you would like to check on the list:

* Remove conditional form settings
* How testing content after a template rendering in a view

**Comment by Riverfount** [comment]
Well, on Oct 31th I'll be in XI International Brazilian Meeting on Cognitive Science and I don't know if I will have the possibility to participate in our next Tech Talk!

**Comment by Riverfount** [comment]
I think that we could discuss these themes:

- Algorithms and analysis of complexity

**Comment by Riverfount** [comment]
Hi guys, 

I think that we'll discuss:

- Algorithms and Analysis of Complexity
- What are the mainly Algorithms when we think of a job interview?
- Is needed to create a Trello Board to manage the project?

Well, I think that's all folks!!

**Comment by renzon** [comment]
Since there are only 3 people really contributing to the project I don't feel the need to add another tool to handle issues. Github is simple but complete enough for this team scale. But if you want connect Trello to learn the tool, go ahead. If the integration with GH is good Trello will not be on the way for those that just only manage issues here ;)

**Comment by Riverfount** [comment]
Ok, @renzon I understand! Follow the use of Git and GitHub do manage the project!
