### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#6]
There are html and css on the original Google App Engine Project

**Comment by tiagocordeiro** [comment]
Do you want to share the html and css that already exists? Or can we think of a new interface for the site?

**Comment by renzon** [comment]
We can do both. Maybe starting with the existing as base and discussing about the home content in a mtg ;)

**Comment by renzon** [comment]
@Riverfount Somethings that I have in mind for Home page: A video where Both I and @ramalho will explain and call people to the course; A section on bottom with mini bios just like current web site www.python.pro.br.

**Comment by renzon** [comment]
When there is no cohort scheduled we are going to have a simple form with name and email so the so interested people can fill and be contact when we decide to schedule a new cohort. I hope those info help you on the design and feel free to reach me any time as always ;)

**Comment by Riverfount** [comment]
@renzon Ok, I'll think about the layout and this information is so cool to guide me!
