### ISSUE TITLE
Import user from Google App Engine Original website

### ISSUE THREAD

**Issue by renzon** [pythonprobr/pythonpro-website#7]

**Comment by Riverfount** [comment]
How can I have access to de Google App Engine to import users to the new project?

**Comment by renzon** [comment]
This will be trick, I need to remember how to that. Is not easy because App Engine uses Datastore a NoSQL database.

**Comment by tiagocordeiro** [comment]
And if you use a json generated from a function in flask, can it work?

**Comment by renzon** [comment]
Unfortunatelly current web site is not using flask. Anyway once this will be a one time migration, probably is better using something like a csv.

**Comment by Riverfount** [comment]
I think we need to concentrate effort to show **outputs**... this importation is **input** and I think we can leave to the future! What do you think?

**Comment by renzon** [comment]
I share @Riverfount opinion. This will be relevant only when we start to have content on the website, because previous students will have access as well. That is the reason I've created this issue, to not forget them ;)
